receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: ${OTEL_NEW_RELIC_EXPORTER_OTLP_ENDPOINT}
    headers:
      api-key: ${OTEL_NEW_RELIC_EXPORTER_API_KEY}
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels: { }

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 50

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors:
        - batch
      exporters: [ otlp ]
    metrics:
      receivers: [ otlp ]
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlp
        - prometheus