package service

import (
	"time"

	"github.com/muchlist/moneymagnet/business/category/model"
	"github.com/muchlist/moneymagnet/pkg/xulid"
)

func generateDefaultCategory(pocketID xulid.ULID) []model.Category {
	timeNow := time.Now()
	ulidInstance := xulid.Instance()
	categories := []model.Category{
		/*INCOME CATEGORY*/
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Salary",
			CategoryIcon: 1,
			IsIncome:     true,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Grants",
			CategoryIcon: 2,
			IsIncome:     true,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Refunds",
			CategoryIcon: 3,
			IsIncome:     true,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Sale",
			CategoryIcon: 4,
			IsIncome:     true,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Rental",
			CategoryIcon: 5,
			IsIncome:     true,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		/*EXPENSE CATEGORY*/
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Baby",
			CategoryIcon: 6,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Beauty",
			CategoryIcon: 7,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Bills",
			CategoryIcon: 8,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Vehicle",
			CategoryIcon: 9,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Clothing",
			CategoryIcon: 10,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Education",
			CategoryIcon: 11,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Electronics",
			CategoryIcon: 12,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Entertainment",
			CategoryIcon: 13,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Food",
			CategoryIcon: 14,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Health",
			CategoryIcon: 15,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Home",
			CategoryIcon: 16,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Insurance",
			CategoryIcon: 17,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Shopping",
			CategoryIcon: 18,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Social",
			CategoryIcon: 19,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Sport",
			CategoryIcon: 20,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Tax",
			CategoryIcon: 21,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Telephone",
			CategoryIcon: 22,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Internet",
			CategoryIcon: 23,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Transportation",
			CategoryIcon: 24,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
		{
			ID:           ulidInstance.NewULID(),
			PocketID:     pocketID,
			CategoryName: "Work",
			CategoryIcon: 25,
			IsIncome:     false,
			CreatedAt:    timeNow,
			UpdatedAt:    timeNow,
		},
	}

	return categories
}
