name: Deploy to Server

on:
  push:
    tags:
      - 'prod-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build
        run: export GOOS=linux GOARCH=amd64; go build -o magnet-api ./app/api
      
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host server\n\tHostName ${{ secrets.SSH_HOST }}\n\tUser ${{ secrets.SSH_USERNAME }}\n\tPort ${{ secrets.SSH_PORT }}\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/deploy_key" > ~/.ssh/config

      - name: Deploy and Restart Service
        run: |
          # Backup
          ssh server 'mv /home/muchlis/app/money-magnet/magnet-api /home/muchlis/app/money-magnet/magnet-api.backup'
          
          # Copy file to server
          scp magnet-api server:/home/muchlis/app/money-magnet/
          
          # Permission
          ssh server 'chmod +x /home/muchlis/app/money-magnet/magnet-api'
          
          # Validation
          ssh server '
            systemctl restart magnet-api && 
            sleep 5 && # Tunggu beberapa detik
            if ! systemctl is-active --quiet magnet-api; then
              # Rollback jika gagal
              cp /home/muchlis/app/money-magnet/magnet-api.backup /home/muchlis/app/money-magnet/magnet-api
              systemctl restart magnet-api
              exit 1
            fi
          '
